### PR TITLE
Fix/test with fw 2.3.4

### LINKED ISSUE #698: Send amount also for segwit transactions in tests
I have tried to [test Connect against Trezor master](https://gitlab.com/satoshilabs/trezor/connect/-/jobs/810851208) and it fails on BTC signing with the message `Failed to decode message: Required field 'amount' was not received`.

This is because of https://github.com/trezor/trezor-firmware/issues/1109 - `amount` is currently required for all transactions. Hopefully this seems to be working in Suite as [reported by our QA](https://github.com/trezor/trezor-firmware/issues/1109#issuecomment-674361614) so this might concern only the tests.

### PR DESCRIPTION
**Pull request by szymonlesisz**
#### this PR should be squashed into 1 commit
fix https://github.com/trezor/connect/issues/698

### CODE REVIEW

File: tests/__fixtures__/signTransactionZcash.js [hunk 1]
```diff
@@ -103,19 +104,21 @@ export default {
                     },
                 ],
             },
-            result: {
-                serializedTx: '030000807082c4030279ac50582b99028697df6b73f2966f8d17867ec57e8f24cde117fac6cd3cf56d010000006b483045022100f960b9c81d873f3dfafa828f8dbbe7ea88eec4fee41e1e7ccd42113e4b185838022050558c9398572d1c5003aac0b796acf1f177474879fa57c259659be1f9f07de70121032fd3a554fc321693de4b7cf66649da7726c4d0d3849a7b947774e04d54e38f91ffffffffe32ef09055993e26e042e07e85cd9fdd787d91c2591e058eb8fce89219d1e1e7000000006a47304402203a1662a30ae7a54b9b44206f1ee70ce7c5545003e932edcc2a60f01e3ecc90cb0220076e2e963518cee173c0f39b783a48f0fd418e99bb8175defd12993b93a83af1012102a1eb5e72ebdf2a6650593167a4c8391d9a37c2df19e1034fd0e4dc5b525696e9ffffffff0240899500000000001976a9142875b160968fae11ca7fdd0174825c812f24f05688aca0860100000000001976a914d32faea5595826da401c0e486418afd51ce7815488ac000000000000000000',
-            },
+            result: false, // since 2.3.3 Failure_DataError Unsupported transaction version.
```
Comment (mroz22) [inline tests/__fixtures__/signTransactionZcash.js:107]: old test could be marked with firmware range for which it works as it is and a new fixture may be added for the new firmware.
Just an idea, no hard requirement :]

**Review by mroz22 — APPROVED** [review]
